name = input ("Enter your name: ")
age = input("Enter your age: ")
height = input("Enter your height: ")
print("========================")
print("| Name: " + name )
print("| Age: " + age )
print("| Height: " + height)
print("========================")
